services:
    itrlibrary.form.type.post:
        class: ITRLibraryBundle\Form\PostType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    itrlibrary.slack_listener:
        class: ITRLibraryBundle\Events\Listener\SlackListener
        arguments:
            - '@cl_slack.api_client'
        tags:
            - { name: kernel.event_listener, event: post.post_create, method: sendSlackMessage }