services:
    itrlibrary.service.mailer:
        class: ITRLibraryBundle\Service\MailerService
        arguments:
            - '@mailer'
            - '@twig'
    itrlibrary.form.type.post:
        class: ITRLibraryBundle\Form\PostType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    itrlibrary.slack_listener:
        class: ITRLibraryBundle\Events\Listener\SlackListener
        arguments:
            - '@cl_slack.api_client'
            - '%itr_library.slack%'
        tags:
            - { name: kernel.event_listener, event: post.post_create, method: sendSlackMessage }
    itrlibrary.service.command:
        class: ITRLibraryBundle\Service\CommandService
